### ISSUE TITLE
ColoredPrinter.print does not behave like System.out.print

### ISSUE THREAD

**Issue by DesertCookie** [dialex/JCDP#21] opened 2019-10-18 20:04 UTC
The Javadoc says `ColoredPrinter.print` is a

> Usual System.out.print

This is not the case for me. Calling it does not immediately print my string; `System.out.print` correctly does in its place. Instead, my string appears with the next output made with `ColoredPrinter.print` or `ColoredPrinter.println` (or their equivalents from `System.out`).  
For now I am using regular `System.out` in its place - I'd rather use `ColoredPrinter` as in the rest of my code though.

Is this a known and fixable error?

**Comment by dialex** [comment] 2019-10-19 11:20
What version are you using of this lib?
What is your operating system?

**Comment by DesertCookie** [comment] 2019-10-19 19:14
I am using JCDP version 2.0.3.1 and Windows 10.  
Sorry, forgot about the OS in the og post *facepalm

**Comment by dialex** [comment] 2019-10-21 14:45
No need to be sorry, it's easy to forget, especially when I don't provide a template for bug reports (but now [I improved it](https://github.com/dialex/JCDP/commit/c8af1ce9e944d19b63a9af983a4d2e0be60c8546), thanks to you 😉)

Regarding your issue, I'm having trouble understanding what your problem is. Here's my current understanding:

You expected `ColoredPrinter.print(msg)` to use `System.out`, because that's what the Javadoc says. But it didn't. You're right, the [implementation](https://github.com/dialex/JCDP/blob/master/src/main/java/com/diogonunes/jcdp/color/impl/WindowsColoredPrinter.java#L167) doesn't match the doc.

- The `UnixColoredPrinter` uses `System.out` to print ([code](https://github.com/dialex/JCDP/blob/master/src/main/java/com/diogonunes/jcdp/color/impl/UnixColoredPrinter.java#L313)).
- The `WindowsColoredPrinter`, your case, uses AnsiConsole from [Jansi](https://github.com/fusesource/jansi) to print ([code](https://github.com/dialex/JCDP/blob/master/src/main/java/com/diogonunes/jcdp/color/impl/WindowsColoredPrinter.java#L333)).

From Jansi's official doc:

> _If the standard out natively supports ANSI escape codes, then this just returns **System.out**, otherwise it will provide an ANSI aware **PrintStream** which strips out the ANSI escape sequences or which implement the escape sequences._

Is that a problem to you? `PrintStream` should work just like `System.out` -- check this [SO question](https://stackoverflow.com/a/14726399/675577).

I can update the Javadoc, besides that I'm not sure what I can do to help you.

**Comment by DesertCookie** [comment] 2019-10-23 20:18
Glad I was the cause of improvement.  
I will investiage and mess around myself to find out why the two calls behave so differently on Windows.

**Comment by dialex** [comment] 2019-10-27 10:51
> _find out why the two calls behave so differently on Windows_

Can you give an example? What do you see that is different? I'm curious.

**Comment by DesertCookie** [comment] 2019-10-28 06:41
As I stated, visually there is no difference, but there is one in behavior, which makes the call to `ColoredPrinter.print` useless (in my usage scenario): it does not print to console immediately after being called, but rather later, when the next print call to (in my case) `System.out` takes place.

**Comment by dialex** [comment] 2019-10-28 08:56
Ah, like it stores the message to print in a buffer and only actually prints it when you call it twice? I checked my unit tests, and it should cover that case ([printing a single message](https://github.com/dialex/JCDP/blob/master/src/test/java/com/diogonunes/jcdp/tests/unit/TestColoredPrinter.java#L140)).

However I only run unit tests for the NIX printer, I should duplicate them for the WIN printer as well. I'll do that this Friday.

**Comment by IncPlusPlus** [comment] 2019-11-04 15:41
Hi @dialex, I'm having the same issue as @DesertCookie with a little twist (you'll see why soon). I'm on Windows 10 and using version 2.0.3.1 of your library. This is awesome, by the way. I appreciate how much effort was put into this library and am grateful for its existence.

Right now, I have a method `info(String message)` that is defined below. Don't worry about the `if(enabled)` checks. It's for the **_very_** simple logger that I made.
```
public static void info(String message) {
		if (enabled) {
			cp.clear();
			cp.println(message, Ansi.Attribute.NONE, Ansi.FColor.CYAN, Ansi.BColor.BLACK);
			cp.clear();
		}
	}
```
This function works perfectly fine. However, if I want to print using this formatter but not have a newline at the end of the message, I have a method `infoNoLine(String message)` defined as follows:
```
public static void infoNoLine(String message) {
		if (enabled) {
			cp.clear();
			cp.print("message", Ansi.Attribute.NONE, Ansi.FColor.CYAN, Ansi.BColor.BLACK);
			cp.clear();
		}
	}
```
Here's where things get interesting. This works perfectly fine for me in Windows' `cmd.exe`. _However_, it does **not** work for me inside of IntelliJ's console window. Instead, nothing is printed at all. I currently have a temporary fix that seems to be doing the job. It works the same as `infoNoLine(String message)` but it works both in IntelliJ and in `cmd.exe`.
```
public static void infoNoLineTempFix(String message) {
		if (enabled) {
			cp.clear();
			//set formatter but don't print anything
			cp.print("", Ansi.Attribute.NONE, Ansi.FColor.CYAN, Ansi.BColor.BLACK);
			//use System.out.print to print the actual message
			System.out.print(message);
			//clear the formatting for whatever might use System.out next
			cp.clear();
		}
	}
```
Let me know if I can provide any other details that might be helpful for fleshing out this issue.

**Comment by dialex** [comment] 2019-11-17 19:52
Thank for your kind words @IncPlusPlus 🙇 

I think I was able to reproduce your issue unit tests on #24. I missed it because I only had for `NIX` printers, _ups!_ The same unit test is passing on Travis (Ubuntu) and failing on IntelliJ (Mac).

I used the unit from the `NIX` and it failed when targeting a `WIN` printer:

<img width="718" alt="Screenshot 2019-11-17 at 19 38 33" src="https://user-images.githubusercontent.com/2140450/69012930-c4bf1400-0972-11ea-806f-93649c560e40.png">

Even though the message output is colored, the test was not able to find the ANSI code. I assumed this was because Jansi had detected that IntelliJ's terminal could not handle ansi codes, so it automatically converted the code to color. That behaviour matches their doc: _"it will provide an ANSI aware PrintStream which strips out the ANSI escape sequences"_.

So I changed the test to assert that the ANSI code is **_not_** in the message. That worked on IntelliJ. When the same test executed on Travis (Ubuntu) it failed:

<img width="964" alt="Screenshot 2019-11-17 at 19 37 08" src="https://user-images.githubusercontent.com/2140450/69012951-db656b00-0972-11ea-8c43-8e0e78bc96d4.png">

Because Travis knows how to handle ANSI codes, Jansi did not handle the code, therefore it was present in the message, thus failing the test. Cross-platform is a headache... 😵

**Comment by dialex** [comment] 2019-11-17 19:56
@IncPlusPlus Can you show the code that use to create and assign `cp`?
Can you try assigning a `new WindowsColoredPrinter...` instead of `new ColoredPrinter...`?

P.S: doing a `cp.clear()` before and after printing is a bit of an overkill, specially if you specify a format on your print message. That will override whatever the current format is.

**Comment by IncPlusPlus** [comment] 2019-11-17 20:01
@dialex Good to know. I'll make some adjustments when I get the chance. Right now I'm using JDCP for debug/logging in a project of mine. [Here](https://github.com/IncPlusPlus/NetProgFinalProject/blob/master/src/main/java/io/github/incplusplus/peerprocessing/logger/StupidSimpleLogger.java) is how it is being used. All my other classes call `info()` `debug()` and `error()`. The reason I have some synchronized methods is to prevent simultaneous calls from printing over each other.

**Comment by dialex** [comment] 2019-11-17 20:06
Nice, public code :) 
So try replacing `ColoredPrinter` with `WindowsColoredPrinter` (line 11) and check if it fixes the IntelliJ issue (I'm assuming is text not colored).

**Comment by IncPlusPlus** [comment] 2019-11-17 20:08
I'll try that when I get the chance. It likely won't be for a day or two. Your assumption is correct. IntelliJ outputs its default white text and is not affected by the ANSI codes that should be included.

**Comment by dialex** [comment] 2019-11-17 20:16
Take your time, I'm already grateful that a student has the patience to debug an open-source dependency of their project! 🙏 

What is bugging me is that, using the same JCDP version you have, my IntelliJ prints colored output (using the example code provided in the Readme). Notice the code (`ColoredPrinter` instance), the java version (`1.8.0.202`), and terminal (with colored msgs):

<img width="1373" alt="Screenshot 2019-11-17 at 20 11 31" src="https://user-images.githubusercontent.com/2140450/69013326-bc68d800-0976-11ea-8b8b-eac4ae54f5d7.png">

Maybe you're using an old version of IntelliJ that doesn't support colors?
I'm using 2019.2.4 (Community Edition) and you?

**Comment by IncPlusPlus** [comment] 2019-11-17 20:20
2019.4 for both CE and Ultimate. I use Ultimate for personal and school projects and CE for work. I might be remembering the output incorrectly. I'll check.

**Comment by dialex** [comment] 2019-11-17 20:25
2019.4???? Are you from the future? 🤣 The latest is 2019.2.4 and they're announcing what's coming on 2019.3, I doubt there's a 2019.4. Check again please.
<img width="856" alt="Screenshot 2019-11-17 at 20 23 00" src="https://user-images.githubusercontent.com/2140450/69013468-32ba0a00-0978-11ea-97a0-e7b79013ed91.png">

**Comment by IncPlusPlus** [comment] 2019-11-17 20:26
Oops! 2019.2.4 🤣

**Comment by IncPlusPlus** [comment] 2019-11-17 20:33
When I launch my project through an IntelliJ run configuration, no colored text ends up in the console. However, if I launch my project using IntelliJ's _terminal_ the colored text _**does**_ appear.

![image](https://user-images.githubusercontent.com/6992149/69013574-659bd800-094f-11ea-8262-c9282ef59f2a.png)
⬆️ Run config ⬆️
⬇️ Launching the project through `mvnw exec:java` ⬇️
![image](https://user-images.githubusercontent.com/6992149/69013575-6c2a4f80-094f-11ea-9a40-1acbc07e0e77.png)

The project SDK version is 11.0.3 and the language level is 11.

**Comment by dialex** [comment] 2019-12-11 16:52
I just released a new version of JCDP ([3.0.0](https://github.com/dialex/JCDP/releases/tag/v3.0.0)) that upgrades Jansi (which I use to print color on Windows). Before I investigate any further, can you (@DesertCookie @IncPlusPlus) please use my new version and tell me if the issue persists?
_P.S: Mind that it requires Java 8, hope it's not a problem 🤞_

**Comment by dialex** [comment] 2019-12-15 19:12
My environment:
- JCDP `3.0.0`
- IntelliJ CE `2019.3` (latest) -> behaves like Windows
- iTerm `3.3.7` on macOS -> behaves like Linux

I tried running the demo code on IntelliJ (to simulate Windows) and iTerm (to simulate Linux) and both printed the expected colors. Can you upgrade JCDP and IntelliJ and confirm if that fixes the issue? Screenshots below.

# IntelliJ (default) as Windows

<img width="1440" alt="Screenshot 2019-12-15 at 19 05 30" src="https://user-images.githubusercontent.com/2140450/70867559-9aab4280-1f6e-11ea-9c38-2a9580607927.png">

# IntelliJ (using Gradle) as Windows

<img width="1440" alt="Screenshot 2019-12-15 at 19 05 37" src="https://user-images.githubusercontent.com/2140450/70867560-9b43d900-1f6e-11ea-8552-0965e14ba8b5.png">

# iTerm (using Gradle) as Linux

<img width="971" alt="Screenshot 2019-12-15 at 19 06 58" src="https://user-images.githubusercontent.com/2140450/70867561-9b43d900-1f6e-11ea-91f9-8a09d9133831.png">

**Comment by dialex** [comment] 2019-12-15 19:22
I also tried exactly your 3 lines of code, on exactly the same way (inside IntelliJ's command line) and still the output was colored as expected:
<img width="712" alt="Screenshot 2019-12-15 at 19 20 07" src="https://user-images.githubusercontent.com/2140450/70867702-0f32b100-1f70-11ea-82c9-beedfadb25d3.png">

**Comment by DesertCookie** [comment] 2019-12-21 21:30
> Before I investigate any further, can you (@DesertCookie @IncPlusPlus) please use my new version and tell me if the issue persists?

My original problem of the printed message not appearing until the next `print` is called still persists. At this point I'm thinking it may be a Java problem, or a me problem.  
I'm calling `ColoredPrinter.print`, then waiting for some input with `Scanner.nextLine`. The input is made, a debug message is printed using `ColoredPrinter.println`. The resulting output would look like this...
```java
userinput
> [DEBUG] message
```
...instead of this...
```java
> userinput
[DEBUG] message
```
. Instead of [print, ENTER, println], it appears [ENTER, print, println] is happening.

Am I just stupid, or is there some seriosly crazy stuff going on?

---

> _P.S: Mind that it requires Java 8, hope it's not a problem 🤞_

I tried both Java 8.0.232 and Java 11.0.5; both worked and yielded the same output and general behavior.

**Comment by dialex** [comment] 2019-12-22 17:08
I'm sorry @DesertCookie, I'm not sure what is the issue and what causes it 🤷‍♂ 
I'll close this topic, if you don't mind.

**Closed as completed by dialex** 2019-12-22 17:08 UTC
Labels: os-win, needs-info
